// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"backendproject/internal/types"
	"github.com/sev-2/raiden/pkg/resource"
)

func RegisterTypes() {
	resource.RegisterTypes(
		&types.Status{},
		&types.UserRole{},
		&types.Doctors{},
		&types.Faskes{},
		&types.Permissions{},
		&types.Poli{},
		&types.ReservationLogs{},
		&types.RolePermissions{},
		&types.Roles{},
		&types.Schedules{},
		&types.Specialties{},
		&types.Status{},
		&types.UserRole{},
		&types.UserRoles{},
	)
}
