PROJECT_NAME: BackendProject
PROJECT_ID: vqmxculxawfltawseqzg
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN: sbp_8f254c0fea2b6daba562e74a2dd3c0d14e78946d
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxbXhjdWx4YXdmbHRhd3NlcXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MDg4MzIsImV4cCI6MjA1NDk4NDgzMn0.rrkx4C2tCVYet5ncUP-b9HQLndXwJ9-RH33ACv_4MCQ
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxbXhjdWx4YXdmbHRhd3NlcXpnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczOTQwODgzMiwiZXhwIjoyMDU0OTg0ODMyfQ.mQlm1nISP1F5EsjZs0C7JYKS7cs6E9WceNg7eBgifaE

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://vqmxculxawfltawseqzg.supabase.co

SERVER_HOST: 127.0.0.1
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
